### ISSUE TITLE
pip install chromadb is failing with error. Using 3.12.1 python kernel

### ISSUE THREAD

**Issue by rveeram** [ksm26/LangChain-Chat-with-Your-Data#1]
Collecting chromadb
  Using cached chromadb-0.4.22-py3-none-any.whl.metadata (7.3 kB)
Collecting build>=1.0.3 (from chromadb)
  Using cached build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: requests>=2.28 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from chromadb) (2.31.0)
Requirement already satisfied: pydantic>=1.9 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from chromadb) (2.5.3)
Collecting chroma-hnswlib==0.7.3 (from chromadb)
  Using cached chroma-hnswlib-0.7.3.tar.gz (31 kB)
  Installing build dependencies ... [?25ldone
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h  Preparing metadata (pyproject.toml) ... [?25ldone
[?25hCollecting fastapi>=0.95.2 (from chromadb)
  Using cached fastapi-0.109.0-py3-none-any.whl.metadata (24 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Using cached uvicorn-0.26.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.22.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from chromadb) (1.26.3)
Collecting posthog>=2.4.0 (from chromadb)
  Using cached posthog-3.3.2-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from chromadb) (4.9.0)
Collecting pulsar-client>=3.1.0 (from chromadb)
  Using cached pulsar_client-3.4.0-cp312-cp312-macosx_10_15_universal2.whl.metadata (1.0 kB)
INFO: pip is looking at multiple versions of chromadb to determine which version is compatible with other requirements. This could take a while.
Collecting chromadb
  Using cached chromadb-0.4.21-py3-none-any.whl.metadata (7.3 kB)
  Using cached chromadb-0.4.20-py3-none-any.whl.metadata (7.3 kB)
  Using cached chromadb-0.4.19-py3-none-any.whl.metadata (7.3 kB)
  Using cached chromadb-0.4.18-py3-none-any.whl.metadata (7.4 kB)
  Using cached chromadb-0.4.17-py3-none-any.whl.metadata (7.3 kB)
  Using cached chromadb-0.4.16-py3-none-any.whl.metadata (7.3 kB)
  Using cached chromadb-0.4.15-py3-none-any.whl.metadata (7.2 kB)
INFO: pip is still looking at multiple versions of chromadb to determine which version is compatible with other requirements. This could take a while.
  Using cached chromadb-0.4.14-py3-none-any.whl.metadata (7.0 kB)
  Using cached chromadb-0.4.13-py3-none-any.whl.metadata (7.0 kB)
  Using cached chromadb-0.4.12-py3-none-any.whl.metadata (7.0 kB)
Collecting pydantic<2.0,>=1.9 (from chromadb)
  Using cached pydantic-1.10.14-py3-none-any.whl.metadata (150 kB)
Collecting fastapi<0.100.0,>=0.95.2 (from chromadb)
  Using cached fastapi-0.99.1-py3-none-any.whl.metadata (23 kB)
Collecting chromadb
  Using cached chromadb-0.4.11-py3-none-any.whl.metadata (7.0 kB)
  Using cached chromadb-0.4.10-py3-none-any.whl.metadata (7.0 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached chromadb-0.4.9-py3-none-any.whl.metadata (7.0 kB)
Collecting chroma-hnswlib==0.7.2 (from chromadb)
  Using cached chroma-hnswlib-0.7.2.tar.gz (31 kB)
  Installing build dependencies ... [?25ldone
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h  Preparing metadata (pyproject.toml) ... [?25ldone
[?25hCollecting chromadb
  Using cached chromadb-0.4.8-py3-none-any.whl.metadata (6.9 kB)
  Using cached chromadb-0.4.7-py3-none-any.whl.metadata (6.9 kB)
  Using cached chromadb-0.4.6-py3-none-any.whl.metadata (6.8 kB)
  Using cached chromadb-0.4.5-py3-none-any.whl.metadata (6.8 kB)
  Using cached chromadb-0.4.4-py3-none-any.whl.metadata (6.8 kB)
  Using cached chromadb-0.4.3-py3-none-any.whl.metadata (6.9 kB)
Collecting pandas>=1.3 (from chromadb)
  Using cached pandas-2.2.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting chroma-hnswlib==0.7.1 (from chromadb)
  Using cached chroma-hnswlib-0.7.1.tar.gz (30 kB)
  Installing build dependencies ... [?25ldone
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h  Preparing metadata (pyproject.toml) ... [?25ldone
[?25hCollecting chromadb
  Using cached chromadb-0.4.2-py3-none-any.whl.metadata (6.9 kB)
  Using cached chromadb-0.4.1-py3-none-any.whl.metadata (6.9 kB)
  Using cached chromadb-0.4.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached chromadb-0.3.29-py3-none-any.whl.metadata (6.9 kB)
Collecting hnswlib>=0.7 (from chromadb)
  Using cached hnswlib-0.8.0.tar.gz (36 kB)
  Installing build dependencies ... [?25ldone
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h  Preparing metadata (pyproject.toml) ... [?25ldone
[?25hCollecting clickhouse-connect>=0.5.7 (from chromadb)
  Using cached clickhouse_connect-0.6.23-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.8 kB)
Collecting duckdb>=0.7.1 (from chromadb)
  Using cached duckdb-0.9.2.tar.gz (10.7 MB)
  Preparing metadata (setup.py) ... [?25ldone
[?25hCollecting fastapi==0.85.1 (from chromadb)
  Using cached fastapi-0.85.1-py3-none-any.whl (55 kB)
Collecting chromadb
  Using cached chromadb-0.3.27-py3-none-any.whl.metadata (6.8 kB)
Collecting pydantic==1.9 (from chromadb)
  Using cached pydantic-1.9.0-py3-none-any.whl (140 kB)
Collecting chromadb
  Using cached chromadb-0.3.26-py3-none-any.whl.metadata (6.8 kB)
  Using cached chromadb-0.3.25-py3-none-any.whl.metadata (6.7 kB)
  Using cached chromadb-0.3.23-py3-none-any.whl.metadata (6.3 kB)
Collecting sentence-transformers>=2.2.2 (from chromadb)
  Using cached sentence-transformers-2.2.2.tar.gz (85 kB)
  Preparing metadata (setup.py) ... [?25ldone
[?25hRequirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from clickhouse-connect>=0.5.7->chromadb) (2023.11.17)
Requirement already satisfied: urllib3>=1.26 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from clickhouse-connect>=0.5.7->chromadb) (2.1.0)
Collecting pytz (from clickhouse-connect>=0.5.7->chromadb)
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting zstandard (from clickhouse-connect>=0.5.7->chromadb)
  Using cached zstandard-0.22.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.9 kB)
Collecting lz4 (from clickhouse-connect>=0.5.7->chromadb)
  Using cached lz4-4.3.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (3.7 kB)
Collecting starlette<0.36.0,>=0.35.0 (from fastapi>=0.95.2->chromadb)
  Using cached starlette-0.35.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/raj/Library/Python/3.12/lib/python/site-packages (from pandas>=1.3->chromadb) (2.8.2)
Collecting tzdata>=2022.7 (from pandas>=1.3->chromadb)
  Using cached tzdata-2023.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/raj/Library/Python/3.12/lib/python/site-packages (from posthog>=2.4.0->chromadb) (1.16.0)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Using cached monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: annotated-types>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic>=1.9->chromadb) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic>=1.9->chromadb) (2.14.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.28->chromadb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests>=2.28->chromadb) (3.6)
Collecting transformers<5.0.0,>=4.6.0 (from sentence-transformers>=2.2.2->chromadb)
  Using cached transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from sentence-transformers>=2.2.2->chromadb) (4.66.1)
INFO: pip is looking at multiple versions of sentence-transformers to determine which version is compatible with other requirements. This could take a while.
Collecting chromadb
  Using cached chromadb-0.3.22-py3-none-any.whl (69 kB)
  Using cached chromadb-0.3.21-py3-none-any.whl (46 kB)
  Using cached chromadb-0.3.20-py3-none-any.whl (46 kB)
  Using cached chromadb-0.3.18-py3-none-any.whl (46 kB)
  Using cached chromadb-0.3.17-py3-none-any.whl (46 kB)
  Using cached chromadb-0.3.16-py3-none-any.whl (46 kB)
  Using cached chromadb-0.3.15-py3-none-any.whl (46 kB)
INFO: pip is still looking at multiple versions of sentence-transformers to determine which version is compatible with other requirements. This could take a while.
  Using cached chromadb-0.3.14-py3-none-any.whl (45 kB)
  Using cached chromadb-0.3.13-py3-none-any.whl (45 kB)
  Using cached chromadb-0.3.12-py3-none-any.whl (45 kB)
  Using cached chromadb-0.3.11-py3-none-any.whl (41 kB)
  Using cached chromadb-0.3.10-py3-none-any.whl (40 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached chromadb-0.3.8-py3-none-any.whl (40 kB)
  Using cached chromadb-0.3.7-py3-none-any.whl (39 kB)
  Using cached chromadb-0.3.6-py3-none-any.whl (39 kB)
  Using cached chromadb-0.3.5-py3-none-any.whl (38 kB)
  Using cached chromadb-0.3.4-py3-none-any.whl (38 kB)
  Using cached chromadb-0.3.3-py3-none-any.whl (38 kB)
  Using cached chromadb-0.3.2-py3-none-any.whl (37 kB)
Collecting pandas~=1.3 (from chromadb)
  Using cached pandas-1.5.3.tar.gz (5.2 MB)
  Installing build dependencies ... [?25ldone
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h  Preparing metadata (pyproject.toml) ... [?25ldone
[?25hCollecting clickhouse-connect~=0.5.7 (from chromadb)
  Using cached clickhouse-connect-0.5.25.tar.gz (70 kB)
  Installing build dependencies ... [?25ldone
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h  Installing backend dependencies ... [?25ldone
[?25h  Preparing metadata (pyproject.toml) ... [?25ldone
[?25hCollecting duckdb~=0.5.1 (from chromadb)
  Using cached duckdb-0.5.1.tar.gz (13.5 MB)
  Preparing metadata (setup.py) ... [?25ldone
[?25hCollecting fastapi~=0.85.1 (from chromadb)
  Using cached fastapi-0.85.2-py3-none-any.whl (55 kB)
Collecting uvicorn~=0.18.3 (from uvicorn[standard]~=0.18.3->chromadb)
  Using cached uvicorn-0.18.3-py3-none-any.whl (57 kB)
Collecting chromadb
  Using cached chromadb-0.3.1-py3-none-any.whl (37 kB)
  Using cached chromadb-0.3.0-py3-none-any.whl (36 kB)
  Using cached chromadb-0.2.0-py3-none-any.whl (36 kB)
Collecting uuid~=1.30 (from chromadb)
  Using cached uuid-1.30.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... [?25ldone
[?25hCollecting chromadb
  Using cached chromadb-0.1.0-py3-none-any.whl (34 kB)
[31mERROR: Cannot install chromadb==0.1.0, chromadb==0.2.0, chromadb==0.3.0, chromadb==0.3.1, chromadb==0.3.2, chromadb==0.3.25, chromadb==0.3.26, chromadb==0.3.27, chromadb==0.3.29, chromadb==0.4.0, chromadb==0.4.1, chromadb==0.4.10, chromadb==0.4.11, chromadb==0.4.12, chromadb==0.4.13, chromadb==0.4.14, chromadb==0.4.15, chromadb==0.4.16, chromadb==0.4.17, chromadb==0.4.18, chromadb==0.4.19, chromadb==0.4.2, chromadb==0.4.20, chromadb==0.4.21, chromadb==0.4.22, chromadb==0.4.3, chromadb==0.4.4, chromadb==0.4.5, chromadb==0.4.6, chromadb==0.4.7, chromadb==0.4.8 and chromadb==0.4.9 because these package versions have conflicting dependencies.[0m[31m
[0m
The conflict is caused by:
    chromadb 0.4.22 depends on onnxruntime>=1.14.1
    chromadb 0.4.21 depends on onnxruntime>=1.14.1
    chromadb 0.4.20 depends on onnxruntime>=1.14.1
    chromadb 0.4.19 depends on onnxruntime>=1.14.1
    chromadb 0.4.18 depends on onnxruntime>=1.14.1
    chromadb 0.4.17 depends on onnxruntime>=1.14.1
    chromadb 0.4.16 depends on onnxruntime>=1.14.1
    chromadb 0.4.15 depends on onnxruntime>=1.14.1
    chromadb 0.4.14 depends on onnxruntime>=1.14.1
    chromadb 0.4.13 depends on onnxruntime>=1.14.1
    chromadb 0.4.12 depends on onnxruntime>=1.14.1
    chromadb 0.4.11 depends on onnxruntime>=1.14.1
    chromadb 0.4.10 depends on onnxruntime>=1.14.1
    chromadb 0.4.9 depends on onnxruntime>=1.14.1
    chromadb 0.4.8 depends on onnxruntime>=1.14.1
    chromadb 0.4.7 depends on onnxruntime>=1.14.1
    chromadb 0.4.6 depends on onnxruntime>=1.14.1
    chromadb 0.4.5 depends on onnxruntime>=1.14.1
    chromadb 0.4.4 depends on onnxruntime>=1.14.1
    chromadb 0.4.3 depends on onnxruntime>=1.14.1
    chromadb 0.4.2 depends on onnxruntime>=1.14.1
    chromadb 0.4.1 depends on onnxruntime>=1.14.1
    chromadb 0.4.0 depends on onnxruntime>=1.14.1
    chromadb 0.3.29 depends on onnxruntime>=1.14.1
    chromadb 0.3.27 depends on onnxruntime>=1.14.1
    chromadb 0.3.26 depends on onnxruntime>=1.14.1
    chromadb 0.3.25 depends on onnxruntime>=1.14.1
    chromadb 0.3.2 depends on numpy~=1.21.6
    chromadb 0.3.1 depends on numpy~=1.21.6
    chromadb 0.3.0 depends on numpy~=1.21.6
    chromadb 0.2.0 depends on numpy~=1.21.6
    chromadb 0.1.0 depends on numpy~=1.21.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts[0m[31m
[0mNote: you may need to restart the kernel to use updated packages.

**Comment by rveeram** [comment]
Not able to install chromadb vectorstore in L3-Vectorstores_and_Embeddings.ipynb.

**Comment by rveeram** [comment]
Running the Jupyter notebook in VS Code using python 3.12.1

**Comment by ksm26** [comment]
The same command works for me, in your message it says

chromadb 0.3.25 depends on onnxruntime>=1.14.1
chromadb 0.3.2 depends on numpy~=1.21.6

you need to install these first I think, also you can paste the contents
into chatgpt and can have a clear explanation.

**Comment by rveeram** [comment]
Chromadb fails with python kernel 3.12. Please use 3.10

**Comment by rveeram** [comment]
issue is with python kernel I was using python 3.12....it works only with
3.10

**Comment by ksm26** [comment]
Ok, thanks for the clarification.
